/* eslint-disable no-template-curly-in-string */
import { expressions as exp } from '../../../lib'

describe('string', () => {
	const context = JSON.parse('{"firstName":"Juan","lastName":"Lopez","email":"jlopez@email.com","age":44,"food":"pizza","film":"Estación central","a":null,"b":"","c":" "}')
	test('lab', () => {
		expect(exp.eval('capitalize(food)', context)).toStrictEqual('Pizza')
		expect(exp.eval('chr(68)', context)).toStrictEqual('D')
		expect(exp.eval('concat(lastName,", ",firstName)', context)).toStrictEqual('Lopez, Juan')
		expect(exp.eval('concatenate(lastName,", ",firstName)', context)).toStrictEqual('Lopez, Juan')
		expect(exp.eval('title(film)', context)).toStrictEqual('Estación Central')
		expect(exp.eval('lower(film)', context)).toStrictEqual('estación central')
		expect(exp.eval('lpad(firstName,10,"_")', context)).toStrictEqual('______Juan')
		expect(exp.eval('ltrim("  a  ")', context)).toStrictEqual('a  ')
		expect(exp.eval('replace(film,"a","*")', context)).toStrictEqual('Est*ción centr*l')
		expect(exp.eval('mask(email)', context)).toStrictEqual('jlo*****com')
		expect(exp.eval('rpad(firstName,10,"_")', context)).toStrictEqual('Juan______')
		expect(exp.eval('rtrim("  a  ")', context)).toStrictEqual('  a')
		expect(exp.eval('substr(film,1,3)', context)).toStrictEqual('st')
		expect(exp.eval('substring(film,1,3)', context)).toStrictEqual('st')
		expect(exp.eval('upper(film)', context)).toStrictEqual('ESTACIÓN CENTRAL')
		expect(exp.eval('startWith(film,"E")', context)).toStrictEqual(true)
		expect(exp.eval('startWith(film,"Est")', context)).toStrictEqual(true)
		expect(exp.eval('startWith(film,"Est",0)', context)).toStrictEqual(true)
		expect(exp.eval('startWith(film,"st",1)', context)).toStrictEqual(true)
		expect(exp.eval('film.startWith("Est")', context)).toStrictEqual(true)
		expect(exp.eval('film.startWith("N")', context)).toStrictEqual(false)
		expect(exp.eval('strCount(film,"a")', context)).toStrictEqual(2)
		expect(exp.eval('`${firstName} is ${age} years old and likes ${food}`', context)).toStrictEqual('Juan is 44 years old and likes pizza')
		expect(exp.eval('test("5","[a-zA-Z0-9_.]+$")', context)).toStrictEqual(true)
		expect(exp.eval('firstName.test("[a-zA-Z0-9_.]+$")', context)).toStrictEqual(true)
		expect(exp.eval('isEmpty(a)', context)).toStrictEqual(true)
		expect(exp.eval('isEmpty(b)', context)).toStrictEqual(true)
		expect(exp.eval('isEmpty(c)', context)).toStrictEqual(true)
		expect(exp.eval('isEmpty(food)', context)).toStrictEqual(false)
		expect(exp.eval('$HOME', context)).toStrictEqual(process.env.HOME)
		expect(exp.eval('${USER}', context)).toStrictEqual(process.env.USER)
		expect(exp.eval('concat($HOME,$USER)', context)).toStrictEqual(`${process.env.HOME}${process.env.USER}`)
		expect(exp.eval('concat(${HOME},$USER)', context)).toStrictEqual(`${process.env.HOME}${process.env.USER}`)
		expect(exp.eval('"Hello"+" "+"world"', context)).toStrictEqual('Hello world')
		expect(exp.eval('`value of home: $HOME`', context)).toStrictEqual(`value of home: ${process.env.HOME}`)
		expect(exp.eval('length(email) > 10 && length(email) < 100', context)).toStrictEqual(true)
		expect(exp.eval('email.length() > 10 && email.length() < 100', context)).toStrictEqual(true)
		expect(exp.eval('isEmpty(b)', context)).toStrictEqual(true)
		expect(exp.eval('isNotEmpty(c)', context)).toStrictEqual(false)
		expect(exp.eval('isNotEmpty(film)', context)).toStrictEqual(true)
	})
})
